language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sbendus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sbendus/docker-react npm run test